export const CHECK = 'CHECK';
export const GETUSERVALUE = 'GETUSERVALUE';
export const GETPASSWORDVALUE = 'GETPASSWORDVALUE';
export const USERNAME = 'USERNAME';
export const PASSWORD = 'PASSWORD';
export const CONFIRMPASSWORD = 'CONFIRMPASSWORD';
